### PR TITLE
handle image error

### PR DESCRIPTION
**Pull request by AgungPrabowo**
screen 1
screen 2
screen 3

### CODE REVIEW

**Comment by mannprerak2** [comment]
Hi @AgungPrabowo 
I think @AlKun25 has also completed this.

@AlKun25 Will you create a PR for this or should I merge this one?

Also, closing a PR will still count for hacktoberfest, (I will not mark this PR as invalid as you have completed worked on this), but I can only merge 1.

**Comment by AlKun25** [comment]
@mannprerak2 I will handle it.

**Comment by mannprerak2** [comment]
Alright then

@AgungPrabowo Thank you for your contribution, it will still be considered for hacktoberfest but I cannot merge it unfortunately, Its partly my fault It should have been assigned to @AlKun25 earlier.

I will close  this PR now, but feel free to checkout any other issue though.

**Comment by AlKun25** [comment]
@mannprerak2 
Also it will be better if all the issues are assigned, so no one makes such mistakes from now on.

**Comment by mannprerak2** [comment]
Can you add a comment on that issue, otherwise it's not letting me assign it to you.

**Comment by AgungPrabowo** [comment]
@mannprerak2 okay thanks, I'm sorry. I'm learning to contribute, please guide me

**Pull request closed without merging**
