### PR TITLE
updated web fav icon

### PR DESCRIPTION
**Pull request by Sirsho29**

### CODE REVIEW

**Comment by mannprerak2** [comment]
@Sirsho29 Could you let me know if this was considered as a PR in your. hacktoberfest dashboard?

**Comment by Sirsho29** [comment]
No it is not added till now.

**Comment by mannprerak2** [comment]
@Sirsho29 
Probably because only the registrations were started i guess

**Comment by Sirsho29** [comment]
Yah maybe. I will try to resolve the other issues after 1st october then.

**Pull request merged**
