### PR TITLE
Placeholder image added

### LINKED ISSUE #4: Add and use a placeholder image
When the image link expires, no image is displayed and a white circle is seen (in thumbnails). Replace this with a placeholder image. 

The placeholder can either be from assets or be a network image, but it must be copyright free.

### PR DESCRIPTION
**Pull request by AlKun25**
Resolved [_Issue #4_](https://github.com/mannprerak2/event_hub_flutter/issues/4)
I have added a placeholder image, but I would advise to use _loading spinner_ as a placeholder. And keep an image for failed to download error.
  Here are its results and how it appears:
  EventList
  EventPage
  SocietyList
  SocietyPage

### CODE REVIEW

**Comment by mannprerak2** [comment]
Hi @AlKun25 
Great work. But I'd request you to use a more subtle image, a big cross catches a lot of attention, which we probably wouldn't want.You can search for error placeholder images and choose something you think is subtle and does not take the user's attention, perhaps something like this https://images.app.goo.gl/tfQGbM1ZERQx5AWEA

Also for your suggestion to use a loader, using a loader for this is not encourage according to material design guidelines and it makes sense, you dont want to see tons of loaders each for one image

And lastly, if you are doing this as part of hacktoberfest, I should remind you only the PRs made during 1st to 31sr October will be counted. (Although the registration has started)
In that case you should close this PR and create a new one after 1st October

**Comment by AlKun25** [comment]
Oh, that's right too about loading spinner. Also I did find images that were more subtle, but I wasn't sure whether they were copyright-free or not. Sorry about that. I will make another PR after 1st Oct with the right image. Will the one you mentioned work?

**Comment by mannprerak2** [comment]
> Will the one you mentioned work?

Not sure, but be sure to use a copyright-free image only, there are many websites for this, don't use Google image search.

**Comment by AlKun25** [comment]
I did find an icon within flutter which is exactly like the image that you shared. Is it ok?

**Comment by mannprerak2** [comment]
Not sure, we'll see when you make the PR.

**Comment by AlKun25** [comment]
### Is this fine? 
image

**Comment by mannprerak2** [comment]
Yes

**Pull request closed without merging**
