### PR TITLE
Customized splash loading screen

### PR DESCRIPTION
**Pull request by skohan**
Customized current splash screen and removed unnecessary text. Please tell me if anything needs to get added.

### CODE REVIEW

**Comment by mannprerak2** [comment]
That's a good start.
However, I think this loader should be placed where the CircularProgressIndicator was before, so that it stays in center.
You can also experiment with adding a very very subtle text animation on "EventHub" (I am sure you can find some package for this as well)
Also please share screenshots/gif of how it looks after the changes.

Note: If you want to make this count for hacktoberfest the PR must be made between 1st to 31st October. In that case, I suggest you close this PR and create a new one between that timeline.

**Comment by skohan** [comment]
On it. I had not tested on mobile. Will fix that.

**Comment by skohan** [comment]
I've added this animation @mannprerak2 . This was the one which worked error-free.
eventhub

**Comment by mannprerak2** [comment]
Looks great 👍

**Pull request closed without merging**
